# Generated by Django 5.0.4 on 2024-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
